enabled: true
image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.5.0
replicas: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
service:
  port: 8080