apiVersion: v2
name: services
description: A Helm chart for deploying microservices
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: authentication-service
    version: 0.1.0
    condition: authentication-service.enabled
  - name: booking-service
    version: 0.1.0
    condition: booking-service.enabled
  - name: notification-service
    version: 0.1.0
    condition: notification.enabled
  - name: test-service
    version: 0.1.0
    condition: test-service.enabled
  - name: ticket-service
    version: 0.1.0
    condition: ticket-service.enabled
  - name: user-service
    version: 0.1.0
    condition: user-service.enabled
