apiVersion: v2
name: services
description: A Helm chart for deploying microservices
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: authentication
    version: 0.1.0
    condition: authentication.enabled
  - name: booking
    version: 0.1.0
    condition: booking.enabled
  - name: notification
    version: 0.1.0
    condition: notification.enabled
  - name: test
    version: 0.1.0
    condition: test.enabled
  - name: ticket
    version: 0.1.0
    condition: ticket.enabled
  - name: user
    version: 0.1.0
    condition: user.enabled
