authentication-service:
  enabled: true
  image: sagiri2k4/ticket-booking-authentication:latest
  port: 8081
booking-service:
  enabled: true
  image: sagiri2k4/ticket-booking-booking:latest
  port: 8082
notification-service:
  enabled: true
  image: sagiri2k4/ticket-booking-notification:latest
  port: 8083
test-service:
  enabled: true
  image: sagiri2k4/ticket-booking-test:latest
  port: 8084
ticket-service:
  enabled: true
  image: sagiri2k4/ticket-booking-ticket:latest
  port: 8085
user-service:
  enabled: true
  image: sagiri2k4/ticket-booking-user:latest
  port: 8086
