server:
  port: 9005

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://mysql:3306/booking_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: mysql
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: broker:9092
    producer:
      properties:
        auto.create.topics.enable: true
        default.replication.factor: 1
    consumer:
      group-id: booking-service

axon:
  axonserver:
    servers: axon-server:8124
    context: default
