image: confluentinc/cp-zookeeper:latest
port: 2181
replicas: 1
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"
service:
  type: ClusterIP
  port: 2181
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
