version: "3.8"

services:
  discovery-server:
    build:
      context: .
      dockerfile: discoveryserver/Dockerfile
    image: ${DOCKER_USERNAME}/discovery-server:latest
    networks:
      - microservice-networks

  authentication-service:
    build:
      context: .
      dockerfile: authenticationservice/Dockerfile
    image: ${DOCKER_USERNAME}/authentication-service:latest
    networks:
      - microservice-networks

  user-service:
    build:
      context: .
      dockerfile: userservice/Dockerfile
    image: ${DOCKER_USERNAME}/user-service:latest
    networks:
      - microservice-networks

  api-gateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    image: ${DOCKER_USERNAME}/api-gateway:latest
    networks:
      - microservice-networks

  ticket-service:
    build:
      context: .
      dockerfile: ticketservice/Dockerfile
    image: ${DOCKER_USERNAME}/ticket-service:latest
    networks:
      - microservice-networks

  booking-service:
    build:
      context: .
      dockerfile: bookingservice/Dockerfile
    image: ${DOCKER_USERNAME}/booking-gateway:latest
    networks:
      - microservice-networks

  test-service:
    build:
      context: .
      dockerfile: testservice/Dockerfile
    image: ${DOCKER_USERNAME}/test-service:latest
    networks:
      - microservice-networks

  notification-service:
    build:
      context: .
      dockerfile: notificationservice/Dockerfile
    image: ${DOCKER_USERNAME}/notification-service:latest
    networks:
      - microservice-networks
networks:
  microservice-networks:
    driver: bridge
