version: "3.8"

services:
  discovery-server:
    build:
      context: .
      dockerfile: discoveryserver/Dockerfile
    image: sagiri2004/ticket-booking-discovery:latest
    networks:
      - microservice-networks

  authentication-service:
    build:
      context: .
      dockerfile: authenticationservice/Dockerfile
    image: sagiri2004/ticket-booking-authentication:latest
    networks:
      - microservice-networks

  user-service:
    build:
      context: .
      dockerfile: userservice/Dockerfile
    image: sagiri2004/ticket-booking-user:latest
    networks:
      - microservice-networks

  api-gateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    image: sagiri2004/ticket-booking-gateway:latest
    networks:
      - microservice-networks

  ticket-service:
    build:
      context: .
      dockerfile: ticketservice/Dockerfile
    image: sagiri2004/ticket-booking-ticket:latest
    networks:
      - microservice-networks

  booking-service:
    build:
      context: .
      dockerfile: bookingservice/Dockerfile
    image: sagiri2004/ticket-booking-booking:latest
    networks:
      - microservice-networks

  test-service:
    build:
      context: .
      dockerfile: testservice/Dockerfile
    image: sagiri2004/ticket-booking-test:latest
    networks:
      - microservice-networks

  notification-service:
    build:
      context: .
      dockerfile: notificationservice/Dockerfile
    image: sagiri2004/ticket-booking-notification:latest
    networks:
      - microservice-networks

networks:
  microservice-networks:
    driver: bridge
