apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels: {{- include "discovery-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{- include "discovery-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "discovery-server.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8761"  # Port mà microservice expose metrics (thường là port chính)
        prometheus.io/path: "/actuator/prometheus"  # Đường dẫn metrics của Spring Boot

    spec:
      containers:
        - name: discovery-server
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
