apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels: {{- include "discovery-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{- include "discovery-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "discovery-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: discovery-server
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
