apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels: {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector: {{- include "api-gateway.selectorLabels" . | nindent 4 }}
