apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels: {{- include "user-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{- include "user-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "user-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: user-service
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
