server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis
      port: 6379
      password: null
      timeout: 2000ms
  cloud:
    gateway:
      discover:
        locator:
          enabled: true

      routes:
        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            #            - name: RequestRateLimiter
            #              args:
            #                redis-rate-limiter.replenishRate: 10
            #                redis-rate-limiter.burstCapacity: 20
            #                redis-rate-limiter.requestedTokens: 1
            - JwtAuthFilter

        # Auth Service
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 10
        #                redis-rate-limiter.burstCapacity: 20
        #                redis-rate-limiter.requestedTokens: 1

        # Test Service
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/api/v1/tests/**
          filters:
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 10
        #                redis-rate-limiter.burstCapacity: 20
        #                redis-rate-limiter.requestedTokens: 1

        # Ticket Service
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/tickets/**
          filters:
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 5
        #                redis-rate-limiter.burstCapacity: 10
        #                redis-rate-limiter.requestedTokens: 1

        # Booking service
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**
          filters:
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 5
        #                redis-rate-limiter.burstCapacity: 10
        #                redis-rate-limiter.requestedTokens: 1

        # Notification service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
        #          filters:
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 5
        #                redis-rate-limiter.burstCapacity: 10
        #                redis-rate-limiter.requestedTokens: 1
        - id: websocket-route
          uri: lb://notification-service
          predicates:
            - Path=/ws/**

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  expirationMs: 86400000

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
      register-with-eureka: true
      fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

