spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: null
      timeout: 2000ms

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true
