server:
  port: 9001

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: mysql

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  expirationMs: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
