image: sagiri2004/ticket-booking-authentication:latest
port: 9001
replicas: 1
resources:
  requests:
    cpu: 400m
    memory: 384Mi
  limits:
    cpu: 800m
    memory: 768Mi
service:
  type: ClusterIP
  port: 9001
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
