# User Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: train-ticket-booking-project-user-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          resources:
            requests:
              cpu: "400m"
              memory: "384Mi"
            limits:
              cpu: "800m"
              memory: "768Mi"