image: mysql:8.0
port: 3306
rootPassword: root
resources:
  requests:
    cpu: 400m
    memory: 384Mi
  limits:
    cpu: 800m
    memory: 768Mi
service:
  type: ClusterIP
  port: 3306
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
