server:
  port: 9006

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: notification-service
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: broker:9092
    producer:
      properties:
        auto.create.topics.enable: true
        default.replication.factor: 1
    consumer:
      group-id: notification-service