apiVersion: v1
kind: Service
metadata:
  name: axon-server
  labels: {{- include "axon-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector: {{- include "axon-server.selectorLabels" . | nindent 4 }}
