{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}
{{- end }}