apiVersion: v2
name: messaging
description: A Helm chart for deploying messaging components (Kafka, Zookeeper)
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kafka
    version: 0.1.0
    condition: kafka.enabled
  - name: zookeeper
    version: 0.1.0
    condition: zookeeper.enabled
