apiVersion: v2
name: messaging
description: A Helm chart for deploying messaging components (broker, Zookeeper)
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: broker
    version: 0.1.0
    condition: broker.enabled
  - name: zookeeper
    version: 0.1.0
    condition: zookeeper.enabled
