apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  labels: {{- include "ticket-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector: {{- include "ticket-service.selectorLabels" . | nindent 4 }}
