apiVersion: v2
name: databases
description: A Helm chart for deploying databases (MySQL, Redis)
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mysql
    version: 0.1.0
    condition: mysql.enabled
  - name: redis
    version: 0.1.0
    condition: redis.enabled
