apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels: { { - include "zookeeper.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.port } }
      protocol: TCP
  selector: { { - include "zookeeper.selectorLabels" . | nindent 4 } }
