image: sagiri2k4/ticket-booking-gateway:latest
replicas: 1
port: 8080
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
service:
  type: NodePort
  port: 8080
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
