# Authentication Service Service
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
    - name: auth-port
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP