apiVersion: v2
name: ticket-booking
description: A Helm chart for deploying the Ticket Booking application with microservices
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: axon-server
    version: 0.1.0
    condition: axon-server.enabled
  - name: databases
    version: 0.1.0
    condition: databases.enabled
  - name: messaging
    version: 0.1.0
    condition: messaging.enabled
  - name: discovery-server
    version: 0.1.0
    condition: discovery-server.enabled
  - name: api-gateway
    version: 0.1.0
    condition: api-gateway.enabled
  - name: services
    version: 0.1.0
    condition: services.enabled
  - name: monitoring
    version: 0.1.0
    condition: monitoring.enabled