apiVersion: v2
name: ticket-booking
description: A Helm chart for deploying the Ticket Booking application with microservices
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies:
  - name: axon
    version: 0.1.0
    condition: axon.enabled
  - name: databases
    version: 0.1.0
    condition: databases.enabled
  - name: messaging
    version: 0.1.0
    condition: messaging.enabled
  - name: discovery
    version: 0.1.0
    condition: discovery.enabled
  - name: gateway
    version: 0.1.0
    condition: gateway.enabled
  - name: services
    version: 0.1.0
    condition: services.enabled
